baseurl: "/minimal-blog"
url: "https://emma-wilson.github.io"

title: Your Name
tagline: Your tagline
profileAltText: Placeholder profile image

bluesky: "#"
linkedin: "#"
orcid: "#"
github: "#"

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md